# Generated by Django 4.2.4 on 2024-01-18 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_following_m2m_fs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fs',
            name='followstatus',
        ),
        migrations.RemoveField(
            model_name='fs',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Following_M2M',
        ),
        migrations.AddField(
            model_name='fs',
            name='follower',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fs',
            name='following',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
